# Generated by Django 2.0.4 on 2018-05-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_auto_20180520_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(height_field='50', null=True, upload_to='mypics/%Y/%m/%d', width_field='100'),
        ),
    ]
