# Generated by Django 2.0.4 on 2018-05-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0003_auto_20180521_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(height_field='url_height', null=True, upload_to='mypics/%Y/%m/%d', width_field='url_width'),
        ),
    ]
